### ISSUE TITLE
Drugs & Consumables Compendium

### ISSUE THREAD

**Issue by Rhundas** [mrkeathley/dark-heresy-2nd-vtt#1]
Noticed that there was a compendium for almost all items from the Core Rulebook with the exception of items under Drugs & Consumables. Is this intentional or upcoming?

**Comment by mrkeathley** [comment]
Not intentional -- it's just a lot and I am still adding features. The force field table was just added yesterday for example. Feel free to put in issues more items I am missing. I will leave this issue open until Drugs/Consumables are completed.

**Comment by Rhundas** [comment]
Will do! Thanks for the response.

**Comment by mrkeathley** [comment]
The items from the core book have been added. Also the consumable type has been added. For now these appear under the gear table. Release with version 1.5.7.
