### ISSUE TITLE
Smite always rolls above the target value.

### ISSUE THREAD

**Issue by HR-Fresco** [mrkeathley/dark-heresy-2nd-vtt#10]
I tried using smite and it always rolls above the target value. I changed the target value to 90 and rolled 150+ times and it failed each time. Laspistol and Invigorate both seem to work normally however.

**Comment by mrkeathley** [comment]
Are you saying that the roll itself does not succeed? If so, I could not replicate it. Maybe you can clarify what issue you were having? I did push up a change related to the psychic barrage so maybe update and make sure you still have the issue.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/10247453/211218300-bd172f41-50ad-4353-89ef-10400e4b423a.png">

**Comment by HR-Fresco** [comment]
Hello, 

It is fixed now. For tracking, the d100 roll would always roll above the target value (failing the test) every time I tried it as well as my pysker player trying it as well.

Thank you for the quick response. I appreciate you making the module

**Comment by mrkeathley** [comment]
Ok, great. I am not sure what the problem was but I am glad it is fixed. Let me know if you find any other issues!
