### ISSUE TITLE
Can't open actor sheets

### ISSUE THREAD

**Issue by Ocaji707** [mrkeathley/dark-heresy-2nd-vtt#11]
Since updating, I haven't been able to open any actors. I tried making a new world, making new actors, and making all three types of actor, but none of them resolved the issue. All modules were disabled. Hosting on the Forge.

**Comment by mrkeathley** [comment]
Which version are you running? I will setup a forge account so I can test it over there and see if something is different that I don't know about.

**Comment by Ocaji707** [comment]
It updated to version 1.6.2

**Comment by Ocaji707** [comment]
and I am on Foundry version 10 build 291

**Comment by mrkeathley** [comment]
I loaded it up in Forge and saw the issue. I just pushed a fix. Let me know if it works after an update.

**Comment by Ocaji707** [comment]
That fixed it, thank you very much!
