### ISSUE TITLE
Can't roll attack with a shotgun due to error fetching scatter modifier

### ISSUE THREAD

**Issue by MattMavis** [mrkeathley/dark-heresy-2nd-vtt#12]
Hi,

First of thanks for creating this system, it great so far!
Second, currently I'm having an issue when it comes to rolling attacks with a shotgun as it seems to error when fetching the scatter effect for the weapon.

![image](https://user-images.githubusercontent.com/52746676/215342139-541d2601-9642-4bea-a3e1-73f23e1811c4.png)

I'd try to fix it myself but I have no JS knowledge.

Currently using the most up to date version of your system. If you need anymore information please ask.

Thanks

**Comment by mrkeathley** [comment]
Thanks for the report. This was a pretty obvious typo. I need to add some scatter weapons to our usual tests. I will push out a new release with this fixed soon.
