### ISSUE TITLE
Mutations are not displayed on character sheets

### ISSUE THREAD

**Issue by elena-v2** [mrkeathley/dark-heresy-2nd-vtt#15]
Within the corruption category on the official character sheets, there's a distinction between malignancies and mutations, and the FVTT system actually has an item type corresponding to mutations, _but_ if a mutation item is added to a character sheet, it will not be displayed in the corruption table on a character sheet. (or at all, for that matter...) This appears to be an oversight!

**Comment by mrkeathley** [comment]
Thanks! I appreciate the help. I will pull that into the next version.
