### ISSUE TITLE
Missing Specialisations for Scholastic Lore

### ISSUE THREAD

**Issue by Rhundas** [mrkeathley/dark-heresy-2nd-vtt#3]
As per page 113 of the DH2 Rulebook, Scholastic Lore specialisations include those from Common Lore.

**Comment by mrkeathley** [comment]
I had some requests to allow for custom specializations as well. So I implemented an add button and prompt that allows for all specializations to have additional skills added. This should allow for any missing ones beyond the defaults to be added if learned. There is no delete yet, but they can be hidden still using the checkboxes.

I think this is better than having a giant baked in list in terms of the UI without rethinking the specialization UI.
