### ISSUE TITLE
Weight for ammunition

### ISSUE THREAD

**Issue by Rhundas** [mrkeathley/dark-heresy-2nd-vtt#9]
Would it be possible to include a weight field on ammunition items (even if it's just empty by default) to allow players to input the weight of ammo?
  Assuming it hasn't been done because there's not really a clean way to distinguish between 'these manstoppers are for my revolver, and these are for my autogun'?
  If it is possible to automate, then a full clip/magazine for a weapon should weigh 10% of the respective weapon's weight as per the 'Standard Ammunition' sidebar on page 166 of the core rulebook.

**Comment by mrkeathley** [comment]
I added the ammunition weight to the sheet as an immediate fix. There is a weapon types field that you can populate that will tell you which weapons it _should_ go with -- but I am not enforcing it at the moment. I like the idea of automating the ammunition weight but I'm not sure how to go about that without having a spot on the weapon for "ammo reserves" or something similar. But I will look into it.

**Comment by mrkeathley** [comment]
I am going to close this issue as the weight is added. Let me know if there is more needed. Thanks!
